name: ${project.name}
author: ${author}
version: ${project.version}
description: ${project.description}
main: ${mainClass}
softdepend: [${softDepend}]
commands:
    hchat:
        description: Manage hChat.
    away:
        description: Flag the player as away.
        aliases: [afk]
    channel:
        description: Chat channels.
        aliases: [ch]
    clearchat:
        description: Clear chat.
    colors:
        description: Get message with color codes.
    me:
        description: Performs the specified action in chat.
    mute:
        description: Mute players.
    unmute:
        description: Unmute players.
    muteall:
        description: Temporarily mute all players muteable.
    unmuteall:
        description: Unmute all players who got muted by muteall command.
    tell:
        description: Sends a private message to the given player.
        aliases: [w, msg, pm]
permissions:
    hchat.*:
        description: All hChat permissions.
        default: op
        children:
            hchat.command.hchat: true
            hchat.command.channel: true
            hchat.command.channel: true
            hchat.command.clearchat: true
            hchat.command.colors: true
            hchat.command.me: true
            hchat.command.mute: true
            hchat.command.unmute: true
            hchat.command.tell: true
            hchat.command.channel.edit.*: true
            hchat.unclearable: true
            hchat.spy: true
            hchat.immutable: true
            hchat.mute.global: true
            hchat.channel.*: true
            hchat.modifyallchannels: true
            hchat.seeallchannels: true
    hchat.command.hchat:
        description: For all subcommands of command hchat.
        children:
            hchat.command.hchat.reload: true
            hchat.command.hchat.list: true
            hchat.command.hchat.update: true
    hchat.command.hchat.reload:
        description: Reload HChat.
    hchat.command.hchat.list:
        description: List info from hChat.
    hchat.command.hchat.reload:
        description: Update hchat to newest version.
    hchat.command.away:
        description: For away command.
    hchat.command.channel:
        description: For all subcommands of command channel.
        children:
            hchat.command.channel.join: true
            hchat.command.channel.leave: true
            hchat.command.channel.list: true
            hchat.command.channel.info: true
            hchat.command.channel.who: true
            hchat.command.channel.create: true
            hchat.command.channel.delete: true
            hchat.command.channel.edit: true
    hchat.command.channel.join:
        description: Join a channel.
    hchat.command.channel.leave:
        description: Leave a channel.
    hchat.command.channel.list:
        description: List all channels.
    hchat.command.channel.info:
        description: Get infor about channel.
    hchat.command.channel.who:
        description: See who is in a channel.
    hchat.command.channel.create:
        description: Create a channel.
    hchat.command.channel.delete:
        description: Delete a channel.
    hchat.command.channel.edit:
        description: Edit a channel.
    hchat.command.channel.edit.*:
        description: Edit all channel properties.
        children:
            hchat.command.channel.edit.name: true
            hchat.command.channel.edit.owner: true
            hchat.command.channel.edit.password: true
            hchat.command.channel.edit.chatformat: true
            hchat.command.channel.edit.private: true
            hchat.command.channel.edit.hidden: true
            hchat.command.channel.edit.censored: true
            hchat.command.channel.edit.colorcodes: true
            hchat.command.channel.edit.universal: true
            hchat.command.channel.edit.autojoinifdefault: true
            hchat.command.channel.edit.range: true
            hchat.command.channel.edit.monitorchannels: true
            hchat.command.channel.edit.membergroups: true
            hchat.command.channel.edit.members: true
            hchat.command.channel.edit.bannedmembers: true
    hchat.command.channel.edit.name:
        description: Edit a channels name.
    hchat.command.channel.edit.owner:
        description: Edit a channels owner.
    hchat.command.channel.edit.password:
        description: Edit a channels password.
    hchat.command.channel.edit.chatformat:
        description: Edit a channels chat format.
    hchat.command.channel.edit.private:
        description: Edit a channels privacy.
    hchat.command.channel.edit.hidden:
        description: Edit a channels visibility.
    hchat.command.channel.edit.censored:
        description: Edit a channels censor setting.
    hchat.command.channel.edit.colorcodes:
        description: Edit a channels color code allowance.
    hchat.command.channel.edit.universal:
        description: Edit a channels universal setting.
    hchat.command.channel.edit.autojoinifdefault:
        description: Edit a channels force auto join setting.
    hchat.command.channel.edit.range:
        description: Edit a channels range setting.
    hchat.command.channel.edit.monitorchannels:
        description: Edit a channels monitored channels.
    hchat.command.channel.edit.membergroups:
        description: Edit a channels member groups.
    hchat.command.channel.edit.members:
        description: Edit a channels members.
    hchat.command.channel.edit.bannedmembers:
        description: Edit a channels banned members.
    hchat.command.clearchat:
        description: For clearchat command.
    hchat.command.colors:
        description: For colors command.
    hchat.command.me:
        description: For me command.
    hchat.command.mute:
        description: For mute command.
    hchat.command.unmute:
        description: For unmute command.
    hchat.command.muteall:
        description: For muteall command.
    hchat.command.unmuteall:
        description: For unmuteall command.
    hchat.command.tell:
        description: For tell command.
    hchat.unclearable:
        description: Unclearable chat.
    hchat.spy:
        description: See all personal messages.
    hchat.immutable:
        description: Player can not be muted.
    hchat.mute.global:
        description: Mute and unmute players globally.
    hchat.mute.list:
        description: List muted players.
    hchat.channel.*:
        description: Access to all channels as a member.
    hchat.notify.update:
        description: Get notified if a plugin update has been found.
    hchat.modifyallchannels:
        description: Modify all channels.
    hchat.seeallchannels:
        description: See all channels.
